name: Daily Commit Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # This runs at midnight UTC every day
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  daily_commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create commit with email 23f1001788@ds.study.iitm.ac.in
        run: |
          echo "Daily commit on $(date)" > daily_commit.txt
          git config --global user.email "23f1001788@ds.study.iitm.ac.in"
          git config --global user.name "DevSync Automation"
          git add daily_commit.txt
          git commit -m "Automated daily commit"
          
      - name: Set remote URL and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Ensure the remote URL is updated with the PAT
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git push origin main  # Ensure this pushes to the correct branch
